# version: "3.9"

services:
  nuxt-notes-app:
    build: .
    container_name: nuxt-notes-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      NITRO_PORT: "3000"
      PORT: "3000"
    restart: unless-stopped
